config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :event_logs do
    resources :comments
  end

  root "event_logs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event_log
end

app/models/event_log.rb
class EventLog < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :body, presence: true
  before_save :parse_ips

  def category(ip)
    octets = ip.split(".").map(&:to_i)
    case octets[0]
    when 10
      "Internal"
    when 172
      octets[1] >= 16 && octets[1] <= 31 ? "Internal" : "External"
    when 192
      octets[1] == 168 ? "Internal" : "External"
    else
      "External"
    end
  end

  def valid_state(ip)
    if ip.match?(/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/)
      octects = ip.split(".").map(&:to_i)
      octects.any? {|oct| oct > 255} ? "Not valid" : "Valid"
    else
      "Not valid"
    end
  end

  private

  def parse_ips
    log = self.body.to_s
    src, dst = "", ""
    log.split(" ").each do |m|
      if m.include?("src")
        self.source_ip = m.split("=")[1]
      elsif m.include?("dst")
        self.dest_ip = m.split("=")[1]
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @event_log = EventLog.find(params[:event_log_id])
    @comment = @event_log.comments.create(comment_params)
    redirect_to event_log_path(@event_log)
  end

  def destroy
    @event_log = EventLog.find(params[:event_log_id])
    @comment = @event_log.comments.find(params[:id])
    @comment.destroy
    redirect_to event_log_path(@event_log), status: 303
  end

  def edit
    @event_log = EventLog.find(params[:event_log_id])
    @comment = @event_log.comments.find(params[:id])
    puts @comment.body.to_s
  end

  def update
    @event_log = EventLog.find(params[:event_log_id])
    @comment = @event_log.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to @event_log
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/event_logs_controller.rb
class EventLogsController < ApplicationController
  def index
    @event_logs = EventLog.all
  end

  def show
    @event_log = EventLog.find(params[:id])
  end

  def new
    @event_log = EventLog.new
  end

  def edit
    @event_log = EventLog.find(params[:id])
  end

  def update
    @event_log = EventLog.find(params[:id])
    if @event_log.update(event_log_params)
      redirect_to @event_log
    else
      render :new, status: :unprocessable_entity
    end
  end

  def create
    @event_log = EventLog.new(event_log_params)
    if @event_log.save
      redirect_to @event_log
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event_log = EventLog.find(params[:id])
    if @event_log.destroy
      redirect_to event_logs_path, status: :see_other
    end
  end

  private

  def event_log_params
    params.require(:event_log).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/event_logs_helper.rb
module EventLogsHelper
end

app/views/comments/_comment.html.erb
<div class="">
  <h6>Comment:</h6>
  <p><%= comment.body %></p>
  <%= link_to "Edit", edit_event_log_comment_path(comment.event_log, comment) %>
  <%= link_to "Delete", [comment.event_log, comment], data:{
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [@event_log, @event_log.comments.build] do |f| %>
  <div class="">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h5>Edit Comment</h5>

<%= @comment.body %>

<%= form_with(model: @comment, url: event_log_comment_path) do |f| %>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<br>
<%= link_to "Event Log", event_log_path(@comment.event_log) %>

app/views/event_logs/_form.html.erb
<%= form_with model: event_log do |f| %>
  <div class="">
    <%= f.label :body %>
    <%= f.text_area :body %>
    <%= event_log.errors.full_messages_for(:body).each do |message| %>
      <div class="">
        <%= message %>
      </div>
    <% end %>
  </div>
  <div class="">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_logs/edit.html.erb
<h5>Edit Event Log</h5>

<%= render "form", event_log: @event_log %>

<br>
<%= link_to "Event Logs", event_logs_path %>

app/views/event_logs/index.html.erb
<h5>Logs:</h5>
<ul>
  <% @event_logs.each do |log| %>
    <li>
      ID: <%= link_to log.id, log %> -
      Source IP(<%= log.category(log.source_ip) %>, <%= log.valid_state(log.source_ip) %>): <%= log.source_ip %> -
      Destination IP(<%= log.category(log.dest_ip) %>, <%= log.valid_state(log.dest_ip) %>): <%= log.dest_ip %>
    </li>
  <% end %>
</ul>

<br>
<%= link_to "New Event Log", new_event_log_path %>

app/views/event_logs/new.html.erb
<h5>New Event Log</h5>

<%= render "form", event_log: @event_log %>

<br>
<%= link_to "Event Logs", event_logs_path %>

app/views/event_logs/show.html.erb
<h5>Log ID: <%= @event_log.id %></h5>
<h5>Source IP(<%= @event_log.category(@event_log.source_ip) %>, <%= @event_log.valid_state(@event_log.source_ip) %>): <%= @event_log.source_ip %></h5>
<h5>Destination IP(<%= @event_log.category(@event_log.dest_ip) %>, <%= @event_log.valid_state(@event_log.dest_ip) %>): <%= @event_log.dest_ip %></h5>
<h5>Body:</h5>
<p><%= @event_log.body %></p>

<br>
<%= link_to "Edit", edit_event_log_path(@event_log) %>
<%= link_to "Event Logs", event_logs_path %>
<%= link_to "Delete", event_log_path(@event_log), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
<br>
<h5>Comments</h5>
<%= render @event_log.comments %>

<br>
<h5>Add a Comment:</h5>
<%= render "comments/form", event_log: @event_log %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LogParser</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1>Event Log Parser(IPv4)</h1>
    <%= yield %>
  </body>
</html>